platform: linux/arm

clone:
  git:
    image: armswarmdrone/git

pipeline:
  build_and_publish:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/postgres
    build_args:
      - PG_PACKAGE=9.6.2-r4
      - PG_VERSION=9.6.2
      - PG_MAJOR=9.6
    tag: [ "9.6.2-alpine", "9.6-alpine", "9-alpine", "alpine" ]
    when:
      branch: master
      event: push

  notify:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
