platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  build_and_publish:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_registry, docker_username, docker_password ]
    repo: quay.io/armswarm/postgres
    build_args:
      - PG_PACKAGE=9.6.5-r0
      - PG_VERSION=9.6.5
      - PG_MAJOR=9.6
    tag: [ "9.6.5-alpine", "9.6-alpine", "9-alpine", "alpine" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
