platform: linux/arm

clone:
  git:
    image: quay.io/armswarm/drone-git

pipeline:
  build_and_publish:
    image: quay.io/armswarm/drone-docker
    secrets: [ docker_registry, docker_username, docker_password ]
    repo: quay.io/armswarm/postgres
    build_args:
      - PG_PACKAGE=10.1-r1
      - PG_VERSION=10.1
      - PG_MAJOR=10
    tag: [ "10.1-alpine", "10-alpine", "alpine" ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
